name: CI

on:
  push:
    paths:
      - "**.py"
      - pyproject.toml
      - uv.lock
      - .github/workflows/ci.yml

jobs:
  lint_and_typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: uv sync
        run: uv sync --frozen --all-extras --dev

      - name: format
        run: uv run ruff format --check

      - name: lint
        run: uv run ruff check

      - name: typecheck
        run: uv run pyright
